<a href="https://colab.research.google.com/github/VietPham1005/Python_Basic/blob/main/DataFrame_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import Files & thư viện Pandas

In [7]:
from google.colab import files
uploaded=files.upload()

Saving mexico-real-estate-1.csv to mexico-real-estate-1.csv
Saving mexico-real-estate-2.csv to mexico-real-estate-2.csv
Saving mexico-real-estate-3.csv to mexico-real-estate-3.csv

In [8]:
import pandas as pd
data1 = pd.read_csv('mexico-real-estate-1.csv')
data2 = pd.read_csv('mexico-real-estate-2.csv')
data3 = pd.read_csv('mexico-real-estate-3.csv')

In [14]:
data3

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.0,263432.41
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67
...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,"20.532264,-103.484418",175.0,121178.91
696,house,|México|Morelos|Jiutepec|,"18.9289862,-99.1802147",100.0,47417.83
697,house,|México|Yucatán|Mérida|,"21.0284038368,-89.6530058049",81.0,39524.23
698,house,|México|San Luis Potosí|San Luis Potosí|,"22.11830417,-101.0321938992",360.0,245050.24
699,house,|México|Estado de México|Toluca|Metepec|,"19.233201,-99.558519",115.0,110667.85

In [24]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            700 non-null    object
 1   place_with_parent_names  700 non-null    object
 2   lat-lon                  582 non-null    object
 3   area_m2                  700 non-null    float64
 4   price_usd                700 non-null    float64
 5   lat                      582 non-null    object
dtypes: float64(2), object(4)
memory usage: 32.9+ KB

#Chuyển dạng dữ liệu float sang String để xử lý

In [25]:
data3['lat-lon']=data3['lat-lon'].astype(str)

#Thêm cột + Tách Split 1 đoạn dữ liệu từ cột cũ

In [39]:
data3['lat'] = data3['lat-lon'].apply(lambda i: i.split(',')[0])
data3

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd,lat
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59,19.52589
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73,19.2640539
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69,19.268629
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,nan,275.0,263432.41,nan
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67,19.511938
...,...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,"20.532264,-103.484418",175.0,121178.91,20.532264
696,house,|México|Morelos|Jiutepec|,"18.9289862,-99.1802147",100.0,47417.83,18.9289862
697,house,|México|Yucatán|Mérida|,"21.0284038368,-89.6530058049",81.0,39524.23,21.0284038368
698,house,|México|San Luis Potosí|San Luis Potosí|,"22.11830417,-101.0321938992",360.0,245050.24,22.11830417
699,house,|México|Estado de México|Toluca|Metepec|,"19.233201,-99.558519",115.0,110667.85,19.233201

In [40]:
data3 = data3.drop('lat',axis=1)
data3

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,nan,275.0,263432.41
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67
...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,"20.532264,-103.484418",175.0,121178.91
696,house,|México|Morelos|Jiutepec|,"18.9289862,-99.1802147",100.0,47417.83
697,house,|México|Yucatán|Mérida|,"21.0284038368,-89.6530058049",81.0,39524.23
698,house,|México|San Luis Potosí|San Luis Potosí|,"22.11830417,-101.0321938992",360.0,245050.24
699,house,|México|Estado de México|Toluca|Metepec|,"19.233201,-99.558519",115.0,110667.85

#Tạo bảng mới từ Bảng có sẵn

In [43]:
data4 = pd.DataFrame(data3)
data4['lat'] = data4['lat-lon'].str.split(",",expand= True)[0]
data4['lon'] = data4['lat-lon'].str.split(",",expand= True)[1]
data4

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd,lat,lon
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59,19.52589,-99.151703
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73,19.2640539,-99.5727534
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69,19.268629,-99.671722
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,nan,275.0,263432.41,nan,None
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67,19.511938,-96.871956
...,...,...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,"20.532264,-103.484418",175.0,121178.91,20.532264,-103.484418
696,house,|México|Morelos|Jiutepec|,"18.9289862,-99.1802147",100.0,47417.83,18.9289862,-99.1802147
697,house,|México|Yucatán|Mérida|,"21.0284038368,-89.6530058049",81.0,39524.23,21.0284038368,-89.6530058049
698,house,|México|San Luis Potosí|San Luis Potosí|,"22.11830417,-101.0321938992",360.0,245050.24,22.11830417,-101.0321938992
699,house,|México|Estado de México|Toluca|Metepec|,"19.233201,-99.558519",115.0,110667.85,19.233201,-99.558519

#Đảo thứ tự cột

In [44]:
new_order=['property_type', 'place_with_parent_names','lat','lon',  'area_m2' , 'price_usd' ]
data4 = data4.reindex(columns = new_order)
data4

,property_type,place_with_parent_names,lat,lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,19.52589,-99.151703,71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,19.2640539,-99.5727534,233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,19.268629,-99.671722,300.0,86932.69
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,nan,None,275.0,263432.41
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,19.511938,-96.871956,84.0,68508.67
...,...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,20.532264,-103.484418,175.0,121178.91
696,house,|México|Morelos|Jiutepec|,18.9289862,-99.1802147,100.0,47417.83
697,house,|México|Yucatán|Mérida|,21.0284038368,-89.6530058049,81.0,39524.23
698,house,|México|San Luis Potosí|San Luis Potosí|,22.11830417,-101.0321938992,360.0,245050.24
699,house,|México|Estado de México|Toluca|Metepec|,19.233201,-99.558519,115.0,110667.85

In [46]:
data2

,property_type,state,lat,lon,area_m2,price_mxn,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,1300000.0,68900.0
1,apartment,Puebla,NaN,NaN,190.0,2500000.0,132500.0
2,house,Morelos,23.634501,-102.552788,360.0,5300000.0,280900.0
3,house,Morelos,NaN,NaN,76.0,820000.0,43460.0
4,house,Puebla,NaN,NaN,200.0,1100000.0,58300.0
...,...,...,...,...,...,...,...
695,house,Morelos,18.917542,-98.963181,140.0,1450000.0,76850.0
696,house,Distrito Federal,19.472128,-99.146697,190.0,1943000.0,102979.0
697,house,Estado de México,19.234984,-99.558175,115.0,2100000.0,111300.0
698,house,Puebla,18.918714,-98.426639,90.0,890000.0,47170.0
699,house,Yucatán,21.075163,-89.516731,185.0,1695000.0,89835.0

#Tính toán cột mới dựa trên cột cũ

In [48]:
data5= pd.DataFrame(data2)
exchange_rate = 0.053
data5['price_usd'] = data5['price_mxn'].apply(lambda x: x * exchange_rate)
data5 = data5.drop('price_mxn',axis=1)
data5

    property_type             state        lat         lon  area_m2  price_usd
0       apartment        Nuevo León  25.721081 -100.345581     72.0    68900.0
1       apartment            Puebla        NaN         NaN    190.0   132500.0
2           house           Morelos  23.634501 -102.552788    360.0   280900.0
3           house           Morelos        NaN         NaN     76.0    43460.0
4           house            Puebla        NaN         NaN    200.0    58300.0
..            ...               ...        ...         ...      ...        ...
695         house           Morelos  18.917542  -98.963181    140.0    76850.0
696         house  Distrito Federal  19.472128  -99.146697    190.0   102979.0
697         house  Estado de México  19.234984  -99.558175    115.0   111300.0
698         house            Puebla  18.918714  -98.426639     90.0    47170.0
699         house           Yucatán  21.075163  -89.516731    185.0    89835.0

[700 rows x 6 columns]